doctrine_migrations:
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        'DoctrineMigrations': '%kernel.project_dir%/migrations'
        'Atsmacode\CardGames': 'modules/card-games/database/migrations'
        'Atsmacode\PokerGame': 'modules/poker-game/database/migrations'
    enable_profiler: false
