services:
  db:
    image: mysql:8.0    #check the mysql version you need for your project
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: aye_poker #you can change the database name here
    secrets:
       - db_root_password
  web:  
    image: php:8.2-apache    #check the php version you need for your project
    build:
      context: .
    ports:
      - "8080:80"    #this line maps your pc port to the container port
    depends_on:
      - db    #this line links this container to the db container
    container_name: aye-poker
    volumes:
      - ./src:/var/www/html/src
      - ./modules/poker-game/app:/var/www/html/modules/poker-game/app
      - ./modules/framework/app:/var/www/html/modules/framework/app
      - ./modules/card-games/app:/var/www/html/modules/card-games/app
      - ./public/build:/var/www/html/public/build
      - ./assets:/var/www/html/assets
      - ./templates:/var/www/html/templates
  mercure:
    image: dunglas/mercure
    restart: unless-stopped
    environment:
      # Uncomment the following line to disable HTTPS
      SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: "!ChangeThisMercureHubJWTSecretKey!"
      MERCURE_SUBSCRIBER_JWT_KEY: "!ChangeThisMercureHubJWTSecretKey!"
      CORS_ALLOWED_ORIGINS: "*"

      # Using mercure:80 here for use within Docker container network. This is the URL used for back-end publishing.
      MERCURE_PUBLISHER_URL: "http://mercure:80/.well-known/mercure"

      # For front-end access
      MERCURE_SUBSCRIBER_URL: "http://localhost/.well-known/mercure"
      MERCURE_EXTRA_DIRECTIVES: "anonymous"
    # Uncomment the following line to enable the development mode
    command: /usr/bin/caddy run --config /etc/caddy/dev.Caddyfile
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost/healthz"]
      timeout: 5s
      retries: 5
      start_period: 60s
    ports:
      - "80:80"
      #- "443:443"
    volumes:
      - mercure_data:/data
      - mercure_config:/config
secrets:
  db_root_password:
    # external: true
    file: ./db_root_password.txt

# version: '3.8'    #check if there is a new docker compose version
volumes:
  mercure_data:
  mercure_config:
