#!/usr/bin/bash
php modules/poker-game/dev/PokerGameApp.php app:create-database -d true
php modules/poker-game/dev/PokerGameApp.php app:build-card-games -d true
php modules/poker-game/dev/PokerGameApp.php app:build-poker-game -d true
