#!/usr/bin/bash

# Symfony migrations
php bin/console doctrine:migrations:migrate -n --all-or-nothing

# The natural & required order to run the migrations for the modules is as follows:

# 1. card-games migrations
php bin/console doctrine:migrations:migrate -n --all-or-nothing --configuration=config/migrations/card_games.yaml

# 2. poker-game migrations
php bin/console doctrine:migrations:migrate -n --all-or-nothing --configuration=config/migrations/poker_game.yaml

# Legacy migrations (should still work)
# php dev/BuildAyePoker.php app:create-database
# php dev/BuildAyePoker.php app:build-card-games
# php dev/BuildAyePoker.php app:build-poker-game
