#!/usr/bin/env bash
cp .env.template.docker .env

docker compose up -d --build
docker exec -it aye-poker php bin/console app:build --docker --no-migration

until docker exec -it aye-poker php bin/console doctrine:migrations:migrate -n --all-or-nothing
do
    echo "Retrying Poker DB migration in 3s... container may not be ready yet"
    sleep 3
done

docker exec -it aye-poker php bin/console doctrine:database:create --connection=poker_game
docker exec -it aye-poker php bin/console doctrine:migrations:migrate -n --all-or-nothing --configuration=config/migrations/card_games.yaml
docker exec -it aye-poker php bin/console doctrine:migrations:migrate -n --all-or-nothing --configuration=config/migrations/poker_game.yaml
docker exec -it aye-poker php bin/console doctrine:fixtures:load --append
