#!/usr/bin/env bash
cp .env.template.docker .env

SECRET_FILE="./db_root_password.txt"

# We need to generate a random password before Docker starts
if [ ! -f "$SECRET_FILE" ]; then
    echo "Generating MySQL root password..."
    # openssl might not be installed, just hard code dev value.
    # openssl rand -hex 12 > "$SECRET_FILE"
    echo "dev_password" > "$SECRET_FILE"
    chmod 600 "$SECRET_FILE"
    echo "Secret generated: $SECRET_FILE"
else
    echo "Secret already exists: $SECRET_FILE"
fi

docker compose up -d --build
docker exec -it aye-poker php bin/console app:devpw
docker exec -it aye-poker php bin/console app:build --docker --no-migration

until docker exec -it aye-poker php bin/console doctrine:migrations:migrate -n --all-or-nothing
do
    echo "Retrying Poker DB migration in 3s... container may not be ready yet"
    sleep 3
done

docker exec -it aye-poker php bin/console doctrine:database:create --connection=poker_game
docker exec -it aye-poker php bin/console doctrine:migrations:migrate -n --all-or-nothing --configuration=config/migrations/card_games.yaml
docker exec -it aye-poker php bin/console doctrine:migrations:migrate -n --all-or-nothing --configuration=config/migrations/poker_game.yaml
