#!/usr/bin/env bash
cp .env.template .env
composer install
php bin/console app:build --no-migration
php bin/console doctrine:database:create --if-not-exists
php bin/console doctrine:migrations:migrate -n
php bin/console doctrine:database:create --connection=poker_game --if-not-exists
php bin/console doctrine:migrations:migrate -n --all-or-nothing --configuration=config/migrations/card_games.yaml
php bin/console doctrine:migrations:migrate -n --all-or-nothing --configuration=config/migrations/poker_game.yaml
php bin/console doctrine:fixtures:load -n
npm install && npm run dev
symfony server:start
