#!/usr/bin/env bash
cp .env.template .env
composer install
php bin/console app:build -m
php bin/console doctrine:migrations:migrate -n
php bin/console doctrine:migrations:migrate -n --all-or-nothing --configuration=config/migrations/card_games.yaml
php bin/console doctrine:migrations:migrate -n --all-or-nothing --configuration=config/migrations/poker_game.yaml
npm install && npm run dev
symfony server:start
