#!/usr/bin/bash
cp .env.template .env
docker compose up -d --build

until docker exec -it aye-poker php bin/console app:build --docker
do
    echo "Retrying Poker DB migration in 3s..."
    sleep 3
done

docker exec -it aye-poker php bin/console doctrine:migrations:migrate -n
