#!/usr/bin/bash
cp .env.template .env

SECRET_FILE="./db_root_password.txt"

# We need to generate a random password before Docker starts
if [ ! -f "$SECRET_FILE" ]; then
    echo "Generating MySQL root password..."
    openssl rand -base64 32 > "$SECRET_FILE"
    chmod 600 "$SECRET_FILE"
    echo "Secret generated: $SECRET_FILE"
else
    echo "Secret already exists: $SECRET_FILE"
fi

docker compose up -d --build
docker exec -it aye-poker php bin/console app:devpw

until docker exec -it aye-poker php bin/console app:build --docker
do
    echo "Retrying Poker DB migration in 3s..."
    sleep 3
done

docker exec -it aye-poker php bin/console doctrine:migrations:migrate -n
